# Probability exercises

## Exercise 1 

Two dices are thrown once and the total score is observed. Use a simulation to find the estimated probability that the total score is even or greater than 7.  A simulation is a repetition of the same experiment multiple times to observe its behavior:

- Run the experiment 1000 times (roll 2 dice 1000 times, and sum the number of both dices).
- Keep track of the number of times that the sum was either greater than 7 or an even number.
- Divide the number from step 2 by the number of iterations (1000).

In [33]:
import numpy as np
import pandas as pd
dice1 = np.random.randint(1,7, 1000)
dice2 = np.random.randint(1,7,1000)

sum_numbers = dice1 + dice2
sum = 0
for i in sum_numbers:
    if (i % 2 == 0) or (i >7):
        sum +=1

probability = sum/1000
print(probability)

0.654


## Exercise 2

A box contains 10 white balls, 20 red balls and 30 green balls. If we take 5 balls from the box with replacement (we take the ball, observe what color it is and put it back into the box). We want to know the probability of:

1. Take 3 white and 2 red.
2. Take all of the same color.

Run the experiment 1000 times and calculate the above probabilities.

In [34]:
import numpy as np
ball_box = {}

# Create the box of balls
for i in range(60):
    if i < 10:
        ball_box[i] = "White"
    elif (i > 9) and (i < 30):
        ball_box[i] = "Red"
    else:
        ball_box[i] = "Green"

print(ball_box)

i=0
n = 0

number_possib_white = 0
number_possib_red = 0
number_possib_green = 0
total_possib_1 = 0
total_possib_2 = 0

for i  in range(1000):
    sorted_five_numbers = np.random.randint(0, 60 , 5)
    print(sorted_five_numbers)

    number_possib_white = np.sum([1 for i in sorted_five_numbers if ball_box[i] =="White"])
    number_possib_red = np.sum([1 for i in sorted_five_numbers if ball_box[i] == "Red"])
    if number_possib_white == 3 and number_possib_red == 2:
        total_possib_1 +=1
    number_possib_green = np.sum([1 for i in sorted_five_numbers if ball_box[i] == "Green"])
    if (number_possib_green == 5) or (number_possib_red ==5) or (number_possib_white ==5):
        total_possib_2 +=1
        
print(f"The total possibility of 3 white balls and 2 red ball is :{total_possib_1} times or {total_possib_1/100} % ")
print(f"The possibility to have all the 5 balls with same color is :{total_possib_2} times or {total_possib_2/100} % ")
print(number_possib_green)








{0: 'White', 1: 'White', 2: 'White', 3: 'White', 4: 'White', 5: 'White', 6: 'White', 7: 'White', 8: 'White', 9: 'White', 10: 'Red', 11: 'Red', 12: 'Red', 13: 'Red', 14: 'Red', 15: 'Red', 16: 'Red', 17: 'Red', 18: 'Red', 19: 'Red', 20: 'Red', 21: 'Red', 22: 'Red', 23: 'Red', 24: 'Red', 25: 'Red', 26: 'Red', 27: 'Red', 28: 'Red', 29: 'Red', 30: 'Green', 31: 'Green', 32: 'Green', 33: 'Green', 34: 'Green', 35: 'Green', 36: 'Green', 37: 'Green', 38: 'Green', 39: 'Green', 40: 'Green', 41: 'Green', 42: 'Green', 43: 'Green', 44: 'Green', 45: 'Green', 46: 'Green', 47: 'Green', 48: 'Green', 49: 'Green', 50: 'Green', 51: 'Green', 52: 'Green', 53: 'Green', 54: 'Green', 55: 'Green', 56: 'Green', 57: 'Green', 58: 'Green', 59: 'Green'}
[46 54 56 45 52]
[ 6  2 44 54 11]
[ 1  5 21 16 58]
[26 16 31 52 20]
[ 3 47 18 21  0]
[28 25 14 13  8]
[ 2 47 27 42 21]
[39  9  4 51 52]
[58 18 53 17 39]
[44 46 31 51 19]
[51 10 34 42  8]
[46 18 39  1 20]
[53 25 40 27  1]
[46 55 15 27 32]
[53  5  1 26 32]
[ 8 31 46 48 3